---
apiVersion: v1
kind: Service
metadata:
  name: "{{ cit_dify_sandbox.project_name }}"
  labels:
    app: "{{ cit_dify_sandbox.project_name }}"
spec:
  type: NodePort
  ports:
    - port: 8194
      targetPort: 8194
  selector:
    app: "{{ cit_dify_sandbox.project_name }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ cit_dify_sandbox.project_name }}"
  labels:
    app: "{{ cit_dify_sandbox.project_name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ cit_dify_sandbox.project_name }}"
  template:
    metadata:
      labels:
        app: "{{ cit_dify_sandbox.project_name }}"
    spec:
      containers:
        - name: "{{ cit_dify_sandbox.project_name }}"
          image: langgenius/dify-sandbox:0.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8194
          envFrom:
            - configMapRef:
                name: "{{ cit_dify_sandbox.project_name }}"
            - secretRef:
                name: "{{ cit_dify_sandbox.project_name }}"
